networks:
  ecommerce_network:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper
    networks:
      - ecommerce_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - ecommerce_network
  
  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ecommerce_network

  big_boys-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: big_boys_hostel
      POSTGRES_PASSWORD: big_boys_hostel_password
      POSTGRES_DB: Big_Boys_db
    volumes:
      - big_boys_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - ecommerce_network

  boys_one-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: boys_user
      POSTGRES_PASSWORD: boys_password
      POSTGRES_DB: boys_db
    volumes:
      - boys_one_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - ecommerce_network

  auth-service:
    build:
      context: ./
    container_name: go-app
    environment:
      - DB_BIG_BOYS_USER=big_boys_hostel
      - DB_BIG_BOYS_PASSWORD=big_boys_hostel_password
      - DB_BIG_BOYS_HOST=big_boys-db  
      - DB_BIG_BOYS_PORT=5432
      - DB_BIG_BOYS_NAME=Big_Boys_db

      - DB_BOYS_ONE_USER=boys_user
      - DB_BOYS_ONE_PASSWORD=boys_password
      - DB_BOYS_ONE_HOST=boys_one-db  
      - DB_BOYS_ONE_PORT=5432
      - DB_BOYS_ONE_NAME=boys_db

      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis:6379
    depends_on:
      - big_boys-db
      - boys_one-db
      - kafka
    ports:
      - "8001:8001"
    networks:
      - ecommerce_network

volumes:
  big_boys_postgres_data:
  boys_one_postgres_data:
  kafka_data:
  zookeeper_data: